### ISSUE TITLE
tga rendering problem

### ISSUE THREAD

**Issue by bariscodefxy** [phpgl/visu#4]
[PHP-Life](https://github.com/bariscodefxy/PHP-Life) Hello, I'm trying to make **Half-Life** in **PHP**. I need to learn, is **visu** renders tga files?

**Comment by mario-deluna** [comment]
The texture loader should theoretically support `TGA`. You can find an example of how to load and display textures here:

https://github.com/phpgl/visu/issues/2

and the documentation from PHP-GLFW can be found here:

https://phpgl.net/API/Texture/Texture2D.html


Do you encounter an error?

**Comment by bariscodefxy** [comment]
> The texture loader should theoretically support `TGA`. You can find an example of how to load and display textures here:
> 
> #2
> 
> and the documentation from PHP-GLFW can be found here:
> 
> https://phpgl.net/API/Texture/Texture2D.html
> 
> Do you encounter an error?

There is no error. Just blank (white) model.

**Comment by mario-deluna** [comment]
Can you provide a piece of example code to reproduce?

**Comment by bariscodefxy** [comment]
> Can you provide a piece of example code to reproduce?

I just using fork of your project [php-towerdefense](https://github.com/phpgl/php-towerdefense)

**Comment by bariscodefxy** [comment]
> https://phpgl.net/API/Texture/Texture2D.html

By the way, my game is 3d but technically models has 2d faces so, this will work or not?

**Comment by mario-deluna** [comment]
> By the way, my game is 3d but technically models has 2d faces so, this will work or not?

Sure there is no technical limitation in that regard.

I've just quickly tested loading a TGA file instead of a PNG in https://github.com/phpgl/visu/issues/2 And it works. 

So TGA images should work perfectly fine. 

PHP-Towerdefense doesn't use any bitmaps / images for its graphics (besides the font).

**Comment by mario-deluna** [comment]
I've you provide me with a repo I can clone to reproduce the issue or a piece of example code I gladly help out.

**Comment by bariscodefxy** [comment]
> 

TGA fine, what about PNG or JPG? Are these works too?

**Comment by mario-deluna** [comment]
Yes we utilise [stb_image.h](https://github.com/nothings/stb/blob/master/stb_image.h) in the background which support the following:

```
JPEG baseline & progressive (12 bpc/arithmetic not supported, same as stock IJG lib)
PNG 1/2/4/8/16-bit-per-channel

TGA (not sure what subset, if a subset)
BMP non-1bpp, non-RLE
PSD (composited view only, no extra channels, 8/16 bit-per-channel)

GIF (*comp always reports as 4-channel)
HDR (radiance rgbE format)
PIC (Softimage PIC)
PNM (PPM and PGM binary only)
```

**Comment by bariscodefxy** [comment]
> I've you provide me with a repo I can clone to reproduce the issue or a piece of example code I gladly help out.

I can show an example...
![image](https://github.com/phpgl/visu/assets/85716242/d07dcd30-c5e2-4cb8-90fc-7d8bf20c4d62)
On my project, in the latest commit. You can see loads map but not loads textures. You can see map files on [here](https://github.com/bariscodefxy/PHP-Life/tree/master/resources/terrain/hl_mp_stalkyard).

**Comment by mario-deluna** [comment]
So the terrain renderer you are using to render the level, is not capable of handling uv mapped textures. Its been build for procedural texturing.

What you need is a renderer that basically just renders a textured object, im looking through my examples If I can find a fitting one.

**Comment by bariscodefxy** [comment]
> So the terrain renderer you are using to render the level, is not capable of handling uv mapped textures. Its been build for procedural texturing.
> 
> What you need is a renderer that basically just renders a textured object, im looking through my examples If I can find a fitting one.

I used also model renderer instead of terrain renderer but samething happened.

**Comment by mario-deluna** [comment]
So I just quickly modified the object renderer for this case consider the following class:

```php
<?php

namespace PHPLife\Renderer;

use GL\Geometry\ObjFileParser;
use VISU\ECS\EntitiesInterface;
use VISU\Graphics\BasicVertexArray;
use VISU\Graphics\GLState;
use VISU\Graphics\Rendering\Pass\CallbackPass;
use VISU\Graphics\Rendering\Pass\CameraData;
use VISU\Graphics\Rendering\Pass\GBufferGeometryPassInterface;
use VISU\Graphics\Rendering\Pass\GBufferPassData;
use VISU\Graphics\Rendering\PipelineContainer;
use VISU\Graphics\Rendering\PipelineResources;
use VISU\Graphics\Rendering\RenderContext;
use VISU\Graphics\Rendering\RenderPass;
use VISU\Graphics\Rendering\RenderPipeline;
use VISU\Graphics\ShaderCollection;
use VISU\Graphics\ShaderProgram;
use VISU\Graphics\Texture;

class LevelSceneryRenderer implements GBufferGeometryPassInterface
{
    private ShaderProgram $sceneryShader;

    private array $vaos = [];
    private array $materials = [];
    private array $diffuseTextures = [];

    public function __construct(
        private GLState $gl,
        private ShaderCollection $shaders,
    )
    {
    }

    public function loadLevelObj(string $path) : void
    {
        $model = new ObjFileParser($path);
        /** @var \GL\Buffer\FloatBuffer */
        $meshes = $model->getMeshes('pnc');

        foreach($meshes as $mesh) {
            $va = new BasicVertexArray($this->gl, [3, 3, 2]);
            $va->upload($mesh->vertices);

            if (!isset($this->vaos[$mesh->material->name])) {
                $this->vaos[$mesh->material->name] = [];
            }

            $this->vaos[$mesh->material->name][] = $va;
            $this->materials[$mesh->material->name] = $mesh->material;
        }

        // load all textures
        foreach($this->materials as $material) {
            if ($material->diffuseTexture) {

                // build a path based on the directory of the path of the obj file and the basename of the texture
                $texturePath = dirname($path) . '/' . basename($material->diffuseTexture->path);

                $this->diffuseTextures[$material->name] = new Texture($this->gl, $material->name);
                $this->diffuseTextures[$material->name]->loadFromFile($texturePath);
            }
        }

        // load the shader
        $this->sceneryShader = $this->shaders->get('scenery');
    }

    public function renderToGBuffer(EntitiesInterface $entities, RenderContext $context, GBufferPassData $gbufferData) : void
    {
        $context->pipeline->addPass(new CallbackPass(
            'SceneryPass',
            // setup
            function(RenderPass $pass, RenderPipeline $pipeline, PipelineContainer $data) use($gbufferData) 
            {
                $pipeline->writes($pass, $gbufferData->renderTarget);
            },
            // execute
            function(PipelineContainer $data, PipelineResources $resources) use($entities) 
            {
                $cameraData = $data->get(CameraData::class);

                $this->sceneryShader->use();
                $this->sceneryShader->setUniformMatrix4f('projection', false, $cameraData->projection);
                $this->sceneryShader->setUniformMatrix4f('view', false, $cameraData->view);
                glEnable(GL_DEPTH_TEST);

                foreach($this->vaos as $material => $vaa) {

                    if (isset($this->diffuseTextures[$material])) {
                        $this->diffuseTextures[$material]->bind(GL_TEXTURE0);
                        $this->sceneryShader->setUniform1i('tex_diffuse', 0);
                    }

                    foreach($vaa as $vao) {
                        $vao->bind();
                        $vao->drawAll();
                    }
                }
            }
        ));
    }
}
```

Load this scenery renderer in your `LevelScene.php`

```php

    /**
     * A scenery renderer
     */
    private LevelSceneryRenderer $sceneryRenderer;
    
     // ...

    /**
     * Constructor
     */
    public function __construct(
        protected GameContainer $container,
        protected string $levelName = 'hl_mp_stalkyard'
    )

     // ...

     $this->terrainRenderer = new TerrainRenderer($container->resolveGL(), $container->resolveShaders());
        $this->sceneryRenderer = new LevelSceneryRenderer($container->resolveGL(), $container->resolveShaders());
        $this->sceneryRenderer->loadLevelObj(VISU_PATH_RESOURCES . '/terrain/' . $this->levelName . '/'. $this->levelName . '.obj');

    // .. don't forget to bind a new geometry renderer:
    
    // $this->renderingSystem->addGeometryRenderer($this->terrainRenderer);
    $this->renderingSystem->addGeometryRenderer($this->sceneryRenderer);
```

Then you will need a scenery shader: 


`scenery.vert.glsl`
```
#version 330 core
layout (location = 0) in vec3 a_position;
layout (location = 1) in vec3 a_normal;
layout (location = 2) in vec2 a_texcoord;

out vec3 v_normal;
out vec3 v_position;
out vec4 v_vposition;
out vec2 v_texcoord;

uniform mat4 projection;
uniform mat4 view;

void main()
{
    mat4 model = mat4(1.0);

    vec4 world_pos = model * vec4(a_position, 1.0);
    v_position = world_pos.xyz;
    v_vposition = view * world_pos;

    v_texcoord = a_texcoord;

    vec3 n = normalize(mat3(model) * a_normal);
    
    v_normal = n;
    
    gl_Position = projection * view * world_pos;
}
```

`scenery.frag.glsl`
```
#version 330 core

#include "visu/gbuffer_layout.glsl"

in vec3 v_normal;
in vec3 v_position;
in vec4 v_vposition;
in vec2 v_texcoord;

uniform sampler2D tex_diffuse;

void main()
{
    gbuffer_albedo = texture(tex_diffuse, v_texcoord).rgb;
    gbuffer_normal = v_normal;
    gbuffer_position = v_position;
    gbuffer_vposition = v_vposition.xyz;
}
```

Tested it quickly, this load the level with the diffuse textures:

![s](https://github.com/phpgl/visu/assets/956212/651c0033-7283-40b1-a2ac-599ba87500bf)


Just keep in mind that this rendering loop is really not optimised, to get a solid framerate you should write put everything into one buffer and chunks meshes together by their material to reduce draw calls. Also consider z sorting, tuning SSAO etc..

**Comment by bariscodefxy** [comment]
Thank you bro. I was writing First Person Controller. I will try.

**Comment by bariscodefxy** [comment]
![image](https://github.com/phpgl/visu/assets/85716242/5b89c076-ea57-448d-a7a1-efc99d9ce62b)
Thanks it's working, I'm already using ALBEDO render mode. I'm closing the issue. Thanks for solution.
